apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ci-app-set
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "300"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - list:
      elements:
      - cluster: prod-cluster
        url: https://kubernetes.default.svc
      - cluster: dr-cluster
        url: https://c111-e.us-east.containers.cloud.ibm.com:31784
  template:
    metadata:
      name: '{{cluster}}-ci-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/iiab-mw-gitops/cluster-gitops.git
        targetRevision: master
        path: ace/environments/ci
      destination:
        server: '{{url}}'