apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-app
  namespace: dev
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - list:
      elements:
      - cluster: prod-cluster
        url: 'https://kubernetes.default.svc'
      - cluster: dr-cluster
        url: 'https://c111-e.us-east.containers.cloud.ibm.com:3178'
  template:
    metadata:
      name: '{{cluster}}-dev-app'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/iiab-mw-gitops/cluster-gitops.git
        targetRevision: master
        path: ace/environments/overlays/dev
      destination:
        server: '{{url}}'
