apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ace-integration-server
  namespace: ci
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem