apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ace-config-pvc
  namespace: ci
spec:
  storageClassName: ibmc-file-gold-gid
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem