apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-repo-ace
data:
  branch: ocp47-2021-2
  host: github.com
  org: cloud-native-toolkit-demos
  owner: cloud-native-toolkit-demos
  parentdir: .
  protocol: https
  repo: cluster-gitops
  url: https://github.com/cloud-native-toolkit-demos/cluster-gitops.git
