kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imagestreams-role
  namespace: ci
rules:
  - verbs:
      - '*'
    apiGroups:
      - build.openshift.io
    resources:
      - buildconfigs
  - verbs:
      - '*'
    apiGroups:
      - image.openshift.io
    resources:
      - imagestreams
  