kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imagestreams-rolebinding
  namespace: ci  
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-cntk-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: imagestreams-role
